export const SWAP_TOKEN = 'SWAP_TOKEN';
export const FINALIZE_SWAP_TOKEN = 'FINALIZE_SWAP_TOKEN';

export const CREATE_BNB_ACCOUNT = 'CREATE_BNB_ACCOUNT';
export const DOWNLOAD_BNB_KEYSTORE = 'DOWNLOAD_BNB_KEYSTORE';

