export const ERROR = 'ERROR';

export const SWAP_TOKEN = 'SWAP_TOKEN';
export const TOKEN_SWAPPED = 'TOKEN_SWAPPED';

export const FINALIZE_SWAP_TOKEN = 'FINALIZE_SWAP_TOKEN';
export const TOKEN_SWAP_FINALIZED = 'TOKEN_SWAP_FINALIZED';

export const CREATE_BNB_ACCOUNT = 'CREATE_BNB_ACCOUNT';
export const BNB_ACCOUNT_CREATED = 'BNB_ACCOUNT_CREATED';

export const DOWNLOAD_BNB_KEYSTORE = 'DOWNLOAD_BNB_KEYSTORE';
export const BNB_KEYSTORE_DOWNLOADED = 'BNB_KEYSTORE_DOWNLOADED';
