export const ERROR = 'ERROR';

export const FETCHED_WITHDRAWAL_FEES = 'FETCHED_WITHDRAWAL_FEES';

export const FETCHED_SWAPS = 'FETCHED_SWAPS';
export const TOKEN_SWAPPED = 'TOKEN_SWAPPED';
export const TOKEN_SWAP_FINALIZED = 'TOKEN_SWAP_FINALIZED';

export const BNB_ACCOUNT_CREATED = 'BNB_ACCOUNT_CREATED';
export const BNB_KEYSTORE_DOWNLOADED = 'BNB_KEYSTORE_DOWNLOADED';
