export const ERROR = 'ERROR';

export const TOKEN_SWAPPED = 'TOKEN_SWAPPED';
export const TOKEN_SWAP_FINALIZED = 'TOKEN_SWAP_FINALIZED';

export const BNB_ACCOUNT_CREATED = 'BNB_ACCOUNT_CREATED';
export const BNB_KEYSTORE_DOWNLOADED = 'BNB_KEYSTORE_DOWNLOADED';
