/* A table for mapping a client address to a generated account. */
create table if not exists client_accounts (
  uuid char(36) primary key,

  /* The type of address. loki or bnb */
  address_type text,

  /* A clients address. This is not generated by us! */
  address text,

  /* The type of generated account. loki or bnb */
  account_type text,

  /* An id to a generated account. account_loki or account_bnb */
  account_uuid char(36),

  created timestamp
);

/*
  Loki accounts.
  We don't generate any loki accounts because we only have 1 wallet-rpc running.
  Instead what we do is generate a new sub-address and store that instead, this acts the same way as making a new wallet.
*/
create table if not exists accounts_loki (
  uuid char(36) primary key,
  address text, -- This is just a unique sub-address for a wallet
  address_index int -- The sub-address index
);

/* BNB accounts that were generated by us */
create table if not exists accounts_bnb (
  uuid char(36) primary key,
  address text,
  encrypted_private_key text,
  salt text,
  created timestamp
);

/* A table of all swaps */
create table if not exists swaps (
  uuid char(36) primary key,

  /* The type of swap: loki_to_bnb or bnb_to_loki */
  type text,

  amount text,
  client_account_uuid char(36),

  /* The transaction hash of the client deposit */
  deposit_transaction_hash text,

  /* The transaction hash of our transfer to the client */
  transfer_transaction_hash text,

  processed boolean,
  created timestamp
);
