/* A table for mapping a client address to a generated account. */
create table if not exists client_accounts (
  uuid char(36) primary key,

  /* The type of address. loki or bnb */
  address_type text,

  /* A clients address. This is not generated by us! */
  address text,

  /* The type of generated account. loki or bnb */
  account_type text,

  /* An id to a generated account. account_loki or account_bnb */
  account_uuid char(36),

  created timestamp
);

/* Loki accounts that were generated by us */
-- Disabled for now until i figure out what needs to be stored
-- create table if not exists accounts_loki (

-- );

/* BNB accounts that were generated by us */
create table if not exists accounts_bnb (
  uuid char(36) primary_key,
  address text,
  encrypted_private_key text,
  salt text,
  created timestamp
);
